CREATE TABLE URL_SHORTENER_DETAILS
(
	USD_ID INT(11) PRIMARY KEY AUTO_INCREMENT,
	ABSOLUTE_URL TEXT,
	TINY_URL VARCHAR(200),
	EXPIRY DATE,
    DESCIPTION VARCHAR(500),
    IS_DISABLED INT(1) NOT NULL DEFAULT 0
);


CREATE TABLE URL_CONFIG
(
	UC_ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    CONSTANT_NAME VARCHAR(100),
    CONSTANT_VALUE VARCHAR(100)
);

INSERT INTO URL_CONFIG(CONSTANT_NAME,CONSTANT_VALUE) 
VALUES('TINY_URL_LENGTH',15);

COMMIT;
